GET http://lumen-api.test/user

###

POST http://lumen-api.test/user
{
    "name": "Artur Júnior",
    "email": "artur.junior@soluti.com.br",
    "password": 123456
}

###

GET http://lumen-api.test/ping

###
